# Generated by Django 4.2.2 on 2023-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_proj', '0002_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
